### ISSUE TITLE
Can you help me on using MPI-ESM1-2-HR AMIP?

### ISSUE THREAD

**Issue by alfernandezUDEC** [lzhenn/cmip6-to-wrfinterm#5]
Hello,

Just a couple of weeks ago I found this GitHub and I was able to run the provided MPI example without issues, from geogrid.exe to wrf.exe. I'm working on simulating high resolution Amazon-Andes dynamics for the recent past (2005-2015) using MPI-ESM1-2-HR files ingested every 6 hours. I aim to particularly use the AMIP model output (e.g. ta_6hrPlevPt_MPI-ESM1-2-HR_amip_r1i1p1f1_gn_200501010600-201001010000.nc) but when I run the "python3 run_c2w.py" I get the error "Error: Invalid scenario: AMIP for model MPI-ESM1-2-HR". 

I started the process by downloading the data from ESGF, then I modified the "config.MPI-ESM1-2-HR.ini" file accordingly and it did not work. Afterwards, I created a Vtable called "MPI-ESM1-2-HR_AMIP.csv" which mirrors "MPI-ESM1-2-HR_HIST.csv" but did not work neither. I also thought that something in the cmip_handler.py should be modified but I did not figure out where to look at. Can you help me?

Thanks
Alfonso Fernández
Universidad de Concepción 
Chile

**Comment by alfernandezUDEC** [comment]
Hi,

Anyone reading this? I switched to historical MPI-ESM1-2-HR but the processor crashes and sends this error: "No variable named 'psl'. Variables on the dataset include ['time', 'lat', 'lat_bnds', 'lon', 'lon_bnds', 'height', 'tas']". Im using these files:

hus_6hrPlevPt_MPI-ESM1-2-HR_historical_r1i1p1f1_gn_200501010600-201001010000.nc
huss_6hrPlevPt_MPI-ESM1-2-HR_historical_r1i1p1f1_gn_200501010600-201001010000.nc
mrsos_6hrPlevPt_MPI-ESM1-2-HR_historical_r1i1p1f1_gn_200501010600-201001010000.nc
ps_6hrLev_MPI-ESM1-2-HR_historical_r1i1p1f1_gn_200501010600-201001010000.nc
psl_6hrPlevPt_MPI-ESM1-2-HR_historical_r1i1p1f1_gn_200501010600-201001010000.nc
ta_6hrPlevPt_MPI-ESM1-2-HR_historical_r1i1p1f1_gn_200501010600-201001010000.nc
tas_6hrPlevPt_MPI-ESM1-2-HR_historical_r1i1p1f1_gn_200501010600-201001010000.nc
tsl_6hrPlevPt_MPI-ESM1-2-HR_historical_r1i1p1f1_gn_200501010600-201001010000.nc
ua_6hrPlevPt_MPI-ESM1-2-HR_historical_r1i1p1f1_gn_200501010600-201001010000.nc
uas_6hrPlevPt_MPI-ESM1-2-HR_historical_r1i1p1f1_gn_200501010600-201001010000.nc
va_6hrPlevPt_MPI-ESM1-2-HR_historical_r1i1p1f1_gn_200501010600-201001010000.nc
vas_6hrPlevPt_MPI-ESM1-2-HR_historical_r1i1p1f1_gn_201001010600-201501010000.nc
zg_6hrPlevPt_MPI-ESM1-2-HR_historical_r1i1p1f1_gn_200501010600-201001010000.nc

Thanks in  advance

**Comment by gpapadch** [comment]
I ran on the exact same issue a couple of days ago. It has to do with these 2 facts:

1) As explained in the readme file, the skin temperature (ts) variable is not available for MPI-ESM1-2-HR historical runs. Thus, if u check the corresponding vtable (the ...HIST.csv file, which is different than the ...SSP.csv file), you'll see that 'tas' is used instead of 'ts' to map that variable.

2) As mentioned in the pull requests in this channel, the code skips repeated variables (e.g., in ...HIST.csv, tas is used to map TT and then again for SKINTEMP). The variable 'psl' is right below this repetition of tas in the .csv file, so this is probably what was causing the issue.

I fixed this by simply commenting lines 121,122 in cmip_handler.py (the lines that do the skipping). 

The issue remains, however, that there is no available skin temperature for the historical runs (for some reason) and thus the WRF variable SKINTEMP has to be handled differently. Some info about this is given in the readme file, but as a newbie I'm still figuring it out :D

**Comment by alfernandezUDEC** [comment]
Jeez, that explains the issue. Thanks a lot. As I could not figured it out I moved to pywinter, using tos for SST and tas for SKINTEMP. I'm still not fully running WRF with these data but at least it works with real.

**Comment by gpapadch** [comment]
If there's a guide for using pywinter with cmip6 (vtables and all) please point me to it, i'm kinda struggling with this too!

**Comment by alfernandezUDEC** [comment]
pywinter is a bit more generalized as it should be able to manage any climate data, so you need to write a script customized for your input. Write me an email to alfernandez@udec.cl and I can share the script I wrote for MPI and a cdo script I wrote for getting tos at the spatial and temporal resolution of the rest of the data. As I said, although I still do not manage to make wrf.exe to work, everything runs fine till real
